config/routes.rb
Rails.application.routes.draw do
 
 
  devise_for :customers, controllers: {
   registrations: "public/customers",
   sessions: "customers/sessions",
   passwords: "customers/passwords"
  }
  devise_for :admin,controllers: {
   sessions: "admins/sessions",
   passwords:     "admins/passwords",
   registrations: "admins/registrations",
  }
  
 
 namespace :admin do
  # get "sign_in", :to => "users/sessions#new"
  root to: "homes#top"
  resources :genres, only:[:index, :create, :edit, :update]
  resources :items, only:[:new, :create, :index, :show, :edit, :update]
  resources :customers, only:[:index, :show, :update, :edit]
  resources :orders, only:[:show]
 end
 
 scope module: :public do
  root to: "homes#top"
  root to: "orders#index"
  root to: "addresses#index"
  get "/about" => "homes#about"
  resources :items, only:[:index, :show]
  resources :cart_items, only:[:index, :update, :destroy, :create]
  delete "cart_items" => "cart_items#destroy_all", as: "destroy_all_cart_items"
  resources :orders, only:[:new, :index, :create]
  post "orders/confirm" => "orders#confirm", as: "confirm_orders"
  get "orders/complete" => "orders#complete", as: "complete_orders"
  get "orders/:id" => "orders#show", as: "order"
  
  resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  get "customers" => "customers#show"
  get "customers/edit" => "customers#edit", as: "edit_customer"
  get "customers/unsubscribe" => "customers#unsubscribe"
  patch "customers/withdrawal" => "customers#withdrawal", as: "withdrawal_customer"
 end
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
  
  def view_address
      "〒" + self.postal_code + " " + self.address + "　" + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  enum is_active: {Available: true, Invalid: false}
  
  def active_for_authentication?
     super && (self.is_active === "Available")
  end
end

app/models/detail.rb
class Detail < ApplicationRecord
  
  belongs_to :order
  
  belongs_to :item
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy
  
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  
  belongs_to :genre
  
  has_many :details, dependent: :destroy
  
  has_many :cart_items, dependent: :destroy
  
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  
  has_many :details, dependent: :destroy
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
   @genre = Genre.new
   @genres = Genre.all
  end
  
  def create
   @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render "index"
    end
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render "edit"
    end
  end
  
  private
   def genre_params
     params.require(:genre).permit(:name)
   end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def index
    @item = Item.page(params[:page])
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end
  
  private
  def item_params
    params.require(:item,).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def show
    @order = Order.find(params[:id])
     if @order.payment == 1
      @payment = "クレジットカード"
     elsif @order.payment == 2
      @payment = "銀行振込"
     end
   @details = @order.details
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
    
    def new
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
 before_action :configure_permitted_parameters, if: :devise_controller?
 

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
 <div class="d-flex align-items-center" style="width:100%; height:100px;">
    <h3><span class="bg-light">ジャンル名</span></h3>
 </div>
   <%= form_with model:@genre, url:admin_genre_path, local:true do |f| %>
    <table style="width:50%;">
     <tr>
       <td>ジャンル名</td>
       <td><%= f.text_field :name %></td>
       <td><input type="submit" class="btn btn-success" value="変更を保存"></td>
     </tr>
    </table>
<% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
 <div class="d-flex align-items-center" style="width:100%; height:100px;">
    <h3><span class="bg-light">ジャンル一覧・追加</span></h3>
 </div>
  <div>
  <table style="width:50%;">
    <tr>
      <%= form_with model:@genre, url: admin_genres_path, local:true do |f| %>
        <td>ジャンル名</td>
        <td><%= f.text_field :name %></td>
        <td><input type="submit" class="btn btn-success" value="新規追加"></td>
      <% end %>
    </tr>
  </table>
  </div><br></br>

<div>
 <table class="table">
  <tbody>
    
    <tr class="bg-light">
      <td class="text-center">ジャンル</td>
      <td></td>
    </tr>
     <% @genres.each do |genre| %>
      <tr>
       <td><%= genre.name %></td>
       <td><a href="/admin/genres/<%= genre.id %>/edit" class="btn btn-success" role="button">編集</a></td>
      </tr>
     <% end %>
  </tbody>
 </table>
</div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="d-flex align-items-center" style="width:100%; height:100px;">
    <h3><span class="bg-light">商品編集</span></h3>
  </div>
<%= form_with model:@item, url: admin_item_path, local: true do |f| %>


<table>
 <tbody>
   <tr>
    <td>商品画像</td>
  　 <!--attachment付け足す-->
    <td><%= f.attachment_field :image %></td>
   </tr>
     <tr>
       <td>商品名</td>
　     <td><%= f.text_field :name %></td>
　   </tr>
　     <tr>
　      <td class="align-top">商品説明</td>
　      <td><%= f.text_area :introduction %></td>
　     </tr>
　       <tr>
　　       <td>ジャンル</td>
　         <!--ジャンル項目付け足す-->
           <td><%= f.collection_select :genre_id, Genre.all, :id, :name, { prompt: "選択してください" } %></td>
         </tr>
           <tr>
　　　       <td>税抜価格</td>
　           <td><%= f.text_field :price %>円</td>
　         </tr>
　           <tr>
　             <td>販売ステータス</td>
　             <!--販売ステータス付け足す-->
　             <td></td>
　</tbody>
</table>
　<!--<%= f.submit "変更を保存" %>-->
　<input type="submit" class="btn btn-success" value="変更を保存">
<% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
 
 <div class="d-flex align-items-center" style="width:100%; height:100px;">
  <h3><span class="bg-light">商品一覧</span></h3>
 </div>
  <div class="text-right" style="width:100%;">
  <a href="/admin/items/new"><i class="fas fa-plus fa-2x"></i></a>
  </div>
　 <table class="table">
　  <thead>
　    <tr class="bg-light">
　      <th>商品ID</th>
　      <th>商品名</th>
　      <th>税抜価格</th>
　      <th>ジャンル</th>
　      <th>ステータス</th>
　    </tr>
　  </thead>
　  　<tbody>
　  　 <% @item.each do |item| %>
　  　  <tr>
　  　    <td><%= item.id %></td>
　  　    <td><%= link_to  item.name, admin_item_path(item.id) %></td>
　  　    <td><%= item.price %></td>
　  　    <td><%= item.genre.name %></td>
　  　    <td><%= item.is_active %></td>
　  　  </tr>
　  　 <% end %>
　  　</tbody>
　</table>
 <%= paginate @item %>
</div>

app/views/admin/items/new.html.erb
<%= form_with model:@item, url: admin_items_path, local: true do |f| %>

<h4>商品画像</h4>
 　<!--attachment付け足す-->
 　<%= f.attachment_field :image %>
 　<h4>商品名</h4>
　<%= f.text_field :name %>
　  <h4>商品説明</h4>
　<%= f.text_area :introduction %>
　　 <h4>ジャンル</h4>
　<!--ジャンル項目付け足す-->
  <%= f.collection_select :genre_id, Genre.all, :id, :name, { prompt: "選択してください" } %>
　　　<h4>税抜価格</h4>
　<%= f.text_field :price %>円
　     <h4>販売ステータス</h4>
　   <!--販売ステータス付け足す-->
　<%= f.submit "新規登録" %>
<% end %>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="d-flex align-items-center" style="width:100%; height:100px;">
    <h3><span class="bg-light">商品詳細</span></h3>
  </div>
 
   <div class="d-inline-block m-5">
    <!--画像付け足す-->
    <%= attachment_image_tag @item, :image, :fill, 300, 250, format:"jpeg",fallback:"noimage-1024x898.png", size:"300x250" %>
   </div>
    <div class="d-inline-block m-5">
      <table>
        <tbody>
          <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>
            <tr>
              <td>商品説明</td>
              <td><%= @item.introduction %></td>
            </tr>
               <tr>
                 <td>ジャンル</td>
                 <td><%= @item.genre.name %></td>
               </tr>
                 <tr>
                   <td>税込価格（税抜価格）</td>
                   <td><%= (@item.price * 1.1).round %>(<%= @item.price %>)円</td>
                 </tr>
                   <tr>
                     <td>販売ステータス</td>
                     <td></td>
                   </tr>
        </tbody>
      </table>
          <!--<%= link_to "編集する", edit_admin_item_path %>-->
         <div class="text-center">
          <a href="/admin/items/<%= @item.id %>/edit" class="btn btn-success" role="button">編集する</a>
         </div>
    </div>
  
</div>

app/views/admin/orders/show.html.erb
<div class="container">
 <div class="d-flex align-items-center" style="width:100%; height:100px;">
   <h3><span class="bg-light">注文履歴詳細</span></h3>
 </div>
  <div class="ml-5">
   <table>
    <tbody>
     <tr>
       <td><strong>購入者</strong></td>
       <td><%= @order.order_name %></td>
     </tr>
       <tr>
         <td><strong>注文日</strong></td>
         <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
       </tr>
         <tr>
           <td><strong>配送先</strong></td>
           <td>
            <div class="list-unstyled">
               <li>〒<%= @order.order_postal_code %>　<%= @order.order_address %></li>
               <li><%= @order.order_name %></li>
            </div>
           </td>
         </tr>
           <tr>
             <td><strong>支払方法</strong></td>
             <td><%= @payment %></td>
           </tr>
             <tr>
               <td><strong>注文ステータス</strong></td>
               <td></td>
             </tr>
    </tbody>
   </table>
 </div>
  
   <div class="d-inline-block m-5">
    <table class="table">
     <thead>
      <tr class="bg-light">
       <td><strong>商品名</strong></td>
       <td><strong>単価(税込)</strong></td>
       <td><strong>数量</strong></td>
       <td><strong>小計</strong></td>
       <td><strong>製作ステータス</strong></td>
      </tr>
     </thead>
       <tbody>
          <% @details.each do |detail| %>
         <tr>
           <td><%= detail.item.name %></td>
           <td><%= (detail.item.price * 1.1).round %></td>
           <td><%= detail.amount %></td>
           <td><%= (detail.item.price * 1.1 * detail.amount).round %></td>
           <td></td>
         </tr>
          <% end %>
       </tbody>
    </table>
   </div>
     <div class="d-inline-block m-5">
      <table>
       <tbody>
        <tr>
          <td><strong>商品合計</strong></td>
          <td><%= @order.total_amount %>円</td>
        </tr>
          <tr>
            <td><strong>送料</strong></td>
            <td><%= @order.shipping %>円</td>
          </tr>
            <tr>
              <td><strong>請求金額合計</strong></td>
              <td><%= @order.total_amount + @order.shipping %>円</td>
            </tr>
       </tbody>
      </table>
     </div>
  
</div>