config/routes.rb
Rails.application.routes.draw do
 
 
  devise_for :customers, controllers: {
   registrations: "public/customers",
   sessions: "customers/sessions",
   passwords: "customers/passwords"
  }
  devise_for :admin,controllers: {
   sessions: "admins/sessions",
   passwords:     "admins/passwords",
   registrations: "admins/registrations",
  }
  
 
 namespace :admin do
  # get "sign_in", :to => "users/sessions#new"
  root to: "homes#top"
  resources :genres, only:[:index, :create, :edit, :update]
  resources :items, only:[:new, :create, :index, :show, :edit, :update]
  resources :customers, only:[:index, :show, :update, :edit]
  resources :orders, only:[:show]
 end
 
 scope module: :public do
  root to: "homes#top"
  root to: "orders#index"
  root to: "addresses#index"
  get "/about" => "homes#about"
  resources :items, only:[:index, :show]
  resources :cart_items, only:[:index, :update, :destroy, :create]
  delete "cart_items" => "cart_items#destroy_all", as: "destroy_all_cart_items"
  resources :orders, only:[:new, :index, :create]
  post "orders/confirm" => "orders#confirm", as: "confirm_orders"
  get "orders/complete" => "orders#complete", as: "complete_orders"
  get "orders/:id" => "orders#show", as: "order"
  
  resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  get "customers" => "customers#show"
  get "customers/edit" => "customers#edit", as: "edit_customer"
  get "customers/unsubscribe" => "customers#unsubscribe"
  patch "customers/withdrawal" => "customers#withdrawal", as: "withdrawal_customer"
 end
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
  
  def view_address
      "〒" + self.postal_code + " " + self.address + "　" + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  enum is_active: {Available: true, Invalid: false}
  
  def active_for_authentication?
     super && (self.is_active === "Available")
  end
end

app/models/detail.rb
class Detail < ApplicationRecord
  
  belongs_to :order
  
  belongs_to :item
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy
  
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  
  belongs_to :genre
  
  has_many :details, dependent: :destroy
  
  has_many :cart_items, dependent: :destroy
  
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  
  has_many :details, dependent: :destroy
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def index
    @item = Item.page(params[:page])
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end
  
  private
  def item_params
    params.require(:item,).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
 before_action :configure_permitted_parameters, if: :devise_controller?
 

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/2aae60316c.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class = "shadow-sm">
      <nav class = "navbar navbar-expand-lg navbar-light">
        <div class = "container">
          <a class = "navbar-brand p-3" href = "/"><%= image_tag("logo.png") %></a>
           <button class = "navbar-toggler" type = "button" data-toggle = "collapse" data-target = "#navbarNavDropdown" aria-controls = "navbarNavDropdown" aria-expanded = "aria-label" = "Toggle navigation">
            <span class = "navbar-toggler-icon"></span>
           </button>
            <div class = "collapse navbar-collapse" id = "navbarNavDropdown">
              <ul class = "navbar-nav ml-auto">
                <% if admin_signed_in? %>
                  <li class ="nav-item"><%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %></li>
                  <li class ="nav-item"><%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %></li>
                  <li class ="nav-item"><%= link_to "注文履歴一覧", "/admin", class: 'nav-link text-dark' %></li>
                  <li class ="nav-item"><%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark' %></li>
                  <li class ="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark'  %></li>
        
                <% elsif customer_signed_in? %>
                  <li class ="nav-item"><%= link_to "マイページ", "/customers", class: 'nav-link text-dark' %></li>
                  <li class ="nav-item"><%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %></li>
                  <li class ="nav-item"><%= link_to "カート", cart_items_path, class: 'nav-link text-dark' %></li>
                  <li class ="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %></li>
                <% else %>
                  <li class ="nav-item"><%= link_to "About", "/about", class: 'nav-link text-dark' %></li>
                  <li class ="nav-item"><%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %></li>
                  <li class ="nav-item"><%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %></li>
                  <li class ="nav-item"><%= link_to "ログイン", customer_session_path, class: 'nav-link text-dark' %></li>
                <% end %>
              </ul>
            </div>
        </div>
      </nav>
    </header>
    <%= yield %>
     <footer class="border-top mt-5" style="height: 30px;"></footer>
  </body>
</html>